# Generated by Django 6.0.3 on 2026-04-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediavault',
            name='file',
        ),
        migrations.AddField(
            model_name='mediavault',
            name='file_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
