# Generated by Django 6.0.3 on 2026-04-05 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('diary', 'Diary'), ('letter', 'Letter')], default='manual', max_length=10)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('event_date', models.DateField(db_index=True)),
                ('is_milestone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
